#!/bin/sh

# ulimit -c unlimited

cd /home/twilight/stable
if test `netstat -na | grep 7900 | grep LISTEN | wc -l` -ne 1; then
  kill -9 `cat login-server_sql.pid`
  ./login-server_sql >& login.log &
fi

if test `netstat -na | grep 6121 | grep LISTEN | wc -l` -ne 1; then
  kill -9 `cat char-server_sql.pid`
  ./char-server_sql >& char.log &
fi

if test `netstat -na | grep 5121 | grep LISTEN | wc -l` -ne 1; then
  kill -9 `cat map-server_sql.pid`
  ./map-server_sql >& map.log &
fi

